In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
from split_image import tile_image
from sklearn.model_selection import train_test_split

In [2]:
path_all = pd.read_csv('csv/path_all.csv', index_col='timestamp', parse_dates=['timestamp'])

In [3]:
len(path_all[~path_all.split_256])

0

In [4]:
df = pd.read_csv('csv/data_256.csv', index_col=['timestamp', 'num'], parse_dates=['timestamp']).sort_index()
data_df = df[df.not_void & df.not_edge & df.not_night & df.valid]

/n/home04/ktoshima/.conda/envs/tf-gpu/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [5]:
data_pick = data_df[data_df.hms_sum > 0]

In [6]:
print("all valid data:", len(data_df))
print("dense data:", len(data_pick))

all valid data: 2126278
dense data: 196964

In [8]:
timestamp_all = np.unique(data_df.index.get_level_values('timestamp').date)
timestamp_pick = np.unique(data_pick.index.get_level_values('timestamp').date)

In [9]:
print(len(timestamp_all))
print(len(timestamp_pick))

599
513

In [13]:
date_train, date_test = train_test_split(timestamp_pick, test_size=0.1)

In [15]:
data_df.loc[:, 'date'] = data_df.index.get_level_values('timestamp').date
data_df.date

/n/home04/ktoshima/.conda/envs/tf-gpu/lib/python3.6/site-packages/pandas/core/indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/n/home04/ktoshima/.conda/envs/tf-gpu/lib/python3.6/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

timestamp            num
2017-07-11 00:00:00  127    2017-07-11
                     128    2017-07-11
                     129    2017-07-11
                     130    2017-07-11
                     131    2017-07-11
                               ...
2020-11-30 19:00:00  178    2020-11-30
                     179    2020-11-30
                     221    2020-11-30
                     343    2020-11-30
                     580    2020-11-30
Name: date, Length: 2126278, dtype: object

In [16]:
np.sort(date_test)

array([datetime.date(2017, 7, 16), datetime.date(2017, 7, 20),
       datetime.date(2017, 8, 4), datetime.date(2017, 8, 23),
       datetime.date(2017, 8, 29), datetime.date(2017, 9, 6),
       datetime.date(2017, 9, 8), datetime.date(2017, 9, 11),
       datetime.date(2017, 9, 14), datetime.date(2017, 9, 18),
       datetime.date(2018, 7, 14), datetime.date(2018, 8, 24),
       datetime.date(2018, 8, 28), datetime.date(2018, 9, 5),
       datetime.date(2018, 9, 8), datetime.date(2018, 9, 11),
       datetime.date(2018, 10, 4), datetime.date(2018, 10, 11),
       datetime.date(2018, 10, 18), datetime.date(2018, 11, 13),
       datetime.date(2018, 11, 19), datetime.date(2018, 11, 24),
       datetime.date(2019, 7, 5), datetime.date(2019, 7, 8),
       datetime.date(2019, 7, 18), datetime.date(2019, 7, 25),
       datetime.date(2019, 7, 29), datetime.date(2019, 8, 10),
       datetime.date(2019, 8, 16), datetime.date(2019, 8, 18),
       datetime.date(2019, 8, 29), datetime.date(2019, 9, 2),
       datetime.date(2019, 9, 6), datetime.date(2019, 9, 11),
       datetime.date(2019, 9, 20), datetime.date(2019, 9, 27),
       datetime.date(2019, 10, 4), datetime.date(2019, 10, 22),
       datetime.date(2019, 11, 10), datetime.date(2019, 11, 18),
       datetime.date(2019, 11, 23), datetime.date(2020, 7, 7),
       datetime.date(2020, 9, 10), datetime.date(2020, 9, 24),
       datetime.date(2020, 9, 26), datetime.date(2020, 10, 8),
       datetime.date(2020, 10, 12), datetime.date(2020, 10, 15),
       datetime.date(2020, 10, 19), datetime.date(2020, 10, 30),
       datetime.date(2020, 11, 1), datetime.date(2020, 11, 7)],
      dtype=object)

In [17]:
data_df[data_df.date.isin(np.sort(date_train)) & (data_df.hms_sum > 0)]

                                                                path_band1  \
timestamp           num
2017-07-11 00:00:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
2017-07-11 00:30:00 364  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    407  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    408  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-11-25 13:30:00 562  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-25 15:00:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-25 15:30:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-26 13:00:00 524  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-27 22:30:00 450  /n/holyscratch01/mickley/hms_vision_data/256x2...

                                                                path_band3  \
timestamp           num
2017-07-11 00:00:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
2017-07-11 00:30:00 364  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    407  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    408  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-11-25 13:30:00 562  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-25 15:00:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-25 15:30:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-26 13:00:00 524  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-27 22:30:00 450  /n/holyscratch01/mickley/hms_vision_data/256x2...

                                                                  path_hms  \
timestamp           num
2017-07-11 00:00:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
2017-07-11 00:30:00 364  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    407  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    408  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-11-25 13:30:00 562  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-25 15:00:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-25 15:30:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-26 13:00:00 524  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-27 22:30:00 450  /n/holyscratch01/mickley/hms_vision_data/256x2...

                         hms_sum  is_dense  not_void  not_edge  not_night  \
timestamp           num
2017-07-11 00:00:00 402      377     False      True      True       True
                    403    27750      True      True      True       True
2017-07-11 00:30:00 364     9137     False      True      True       True
                    407      120     False      True      True       True
                    408      145     False      True      True       True
...                          ...       ...       ...       ...        ...
2020-11-25 13:30:00 562       85     False      True      True       True
2020-11-25 15:00:00 363       40     False      True      True       True
2020-11-25 15:30:00 363       40     False      True      True       True
2020-11-26 13:00:00 524       40     False      True      True       True
2020-11-27 22:30:00 450      500     False      True      True       True

                         row_17  col_39  valid        date
timestamp           num
2017-07-11 00:00:00 402      10      12   True  2017-07-11
                    403      10      13   True  2017-07-11
2017-07-11 00:30:00 364       9      13   True  2017-07-11
                    407      10      17   True  2017-07-11
                    408      10      18   True  2017-07-11
...                         ...     ...    ...         ...
2020-11-25 13:30:00 562      14      16   True  2020-11-25
2020-11-25 15:00:00 363       9      12   True  2020-11-25
2020-11-25 15:30:00 363       9      12   True  2020-11-25
2020-11-26 13:00:00 524      13      17   True  2020-11-26
2020-11-27 22:30:00 450      11      21   True  2020-11-27

[179845 rows x 12 columns]

In [18]:
data_df[data_df.date.isin(np.sort(date_test)) & (data_df.hms_sum > 0)]

                                                                path_band1  \
timestamp           num
2017-07-16 00:00:00 173  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    174  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    175  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    176  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    177  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-11-01 23:30:00 408  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    448  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-07 22:00:00 373  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-07 23:00:00 370  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    410  /n/holyscratch01/mickley/hms_vision_data/256x2...

                                                                path_band3  \
timestamp           num
2017-07-16 00:00:00 173  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    174  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    175  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    176  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    177  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-11-01 23:30:00 408  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    448  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-07 22:00:00 373  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-07 23:00:00 370  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    410  /n/holyscratch01/mickley/hms_vision_data/256x2...

                                                                  path_hms  \
timestamp           num
2017-07-16 00:00:00 173  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    174  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    175  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    176  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    177  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-11-01 23:30:00 408  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    448  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-07 22:00:00 373  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-11-07 23:00:00 370  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    410  /n/holyscratch01/mickley/hms_vision_data/256x2...

                         hms_sum  is_dense  not_void  not_edge  not_night  \
timestamp           num
2017-07-16 00:00:00 173    87535     False      True      True       True
                    174   239230     False      True      True       True
                    175   293103     False      True      True       True
                    176   418206     False      True      True       True
                    177   389409     False      True      True       True
...                          ...       ...       ...       ...        ...
2020-11-01 23:30:00 408     1200     False      True      True       True
                    448     5245     False      True      True       True
2020-11-07 22:00:00 373       50     False      True      True       True
2020-11-07 23:00:00 370      320     False      True      True       True
                    410      175     False      True      True       True

                         row_17  col_39  valid        date
timestamp           num
2017-07-16 00:00:00 173       4      17   True  2017-07-16
                    174       4      18   True  2017-07-16
                    175       4      19   True  2017-07-16
                    176       4      20   True  2017-07-16
                    177       4      21   True  2017-07-16
...                         ...     ...    ...         ...
2020-11-01 23:30:00 408      10      18   True  2020-11-01
                    448      11      19   True  2020-11-01
2020-11-07 22:00:00 373       9      22   True  2020-11-07
2020-11-07 23:00:00 370       9      19   True  2020-11-07
                    410      10      20   True  2020-11-07

[17119 rows x 12 columns]

In [15]:
data_df[data_df.date.isin(np.sort(date_train)) & (data_df.hms_sum > 0)]

                                                                path_band1  \
timestamp           num
2017-07-11 00:00:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
2017-07-11 00:30:00 364  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    407  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    408  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-10-26 14:30:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    441  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    442  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-10-26 15:00:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...

                                                                path_band3  \
timestamp           num
2017-07-11 00:00:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
2017-07-11 00:30:00 364  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    407  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    408  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-10-26 14:30:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    441  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    442  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-10-26 15:00:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...

                                                                  path_hms  \
timestamp           num
2017-07-11 00:00:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
2017-07-11 00:30:00 364  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    407  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    408  /n/holyscratch01/mickley/hms_vision_data/256x2...
...                                                                    ...
2020-10-26 14:30:00 402  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    403  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    441  /n/holyscratch01/mickley/hms_vision_data/256x2...
                    442  /n/holyscratch01/mickley/hms_vision_data/256x2...
2020-10-26 15:00:00 363  /n/holyscratch01/mickley/hms_vision_data/256x2...

                         hms_sum  is_dense  not_void  not_edge  not_night  \
timestamp           num
2017-07-11 00:00:00 402      377     False      True      True       True
                    403    27750      True      True      True       True
2017-07-11 00:30:00 364     9137     False      True      True       True
                    407      120     False      True      True       True
                    408      145     False      True      True       True
...                          ...       ...       ...       ...        ...
2020-10-26 14:30:00 402   294788      True      True      True       True
                    403   128122      True      True      True       True
                    441    77985     False      True      True       True
                    442   139109      True      True      True       True
2020-10-26 15:00:00 363      586     False      True      True       True

                         row_17  col_39  valid        date
timestamp           num
2017-07-11 00:00:00 402      10      12   True  2017-07-11
                    403      10      13   True  2017-07-11
2017-07-11 00:30:00 364       9      13   True  2017-07-11
                    407      10      17   True  2017-07-11
                    408      10      18   True  2017-07-11
...                         ...     ...    ...         ...
2020-10-26 14:30:00 402      10      12   True  2020-10-26
                    403      10      13   True  2020-10-26
                    441      11      12   True  2020-10-26
                    442      11      13   True  2020-10-26
2020-10-26 15:00:00 363       9      12   True  2020-10-26

[172479 rows x 12 columns]

## Valid tiles

In [11]:
# data_df['valid'] = (
#     ~(data_df['row_17'] <= 2)
#     & ~(data_df['col_39'] <= 2)
#     & ~((data_df['row_17'] <= 12) & (data_df['col_39'] <= 3))
#     & ~((data_df['row_17'] <= 9) & (data_df['col_39'] <= 4))
#     & ~((data_df['row_17'] <= 8) & (data_df['col_39'] <= 5))
#     & ~((data_df['row_17'] <= 5) & (data_df['col_39'] <= 6))
#     & ~((data_df['row_17'] <= 3) & (data_df['col_39'] <= 9))
#     & ~(tile_num-3 <= data_df['col_39'])
#     & ~((data_df['row_17'] <= 12) & (tile_num-4 <= data_df['col_39']))
#     & ~((data_df['row_17'] <= 8) & (tile_num-5 <= data_df['col_39']))
#     & ~((data_df['row_17'] <= 6) & (tile_num-6 <= data_df['col_39']))
#     & ~((data_df['row_17'] <= 4) & (tile_num-8 <= data_df['col_39']))
#     & ~((data_df['row_17'] <= 3) & (tile_num-9 <= data_df['col_39']))
# )

In [12]:
valid_index = (
    data_df.not_void & data_df.not_edge & data_df.not_night
    & ~(data_df['row_17'] <= 2)
    & ~(data_df['col_39'] <= 2)
    & ~((data_df['row_17'] <= 12) & (data_df['col_39'] <= 3))
    & ~((data_df['row_17'] <= 9) & (data_df['col_39'] <= 4))
    & ~((data_df['row_17'] <= 8) & (data_df['col_39'] <= 5))
    & ~((data_df['row_17'] <= 5) & (data_df['col_39'] <= 6))
    & ~((data_df['row_17'] <= 3) & (data_df['col_39'] <= 9))
    & ~(tile_num-3 <= data_df['col_39'])
    & ~((data_df['row_17'] <= 12) & (tile_num-4 <= data_df['col_39']))
    & ~((data_df['row_17'] <= 8) & (tile_num-5 <= data_df['col_39']))
    & ~((data_df['row_17'] <= 6) & (tile_num-6 <= data_df['col_39']))
    & ~((data_df['row_17'] <= 4) & (tile_num-8 <= data_df['col_39']))
    & ~((data_df['row_17'] <= 3) & (tile_num-9 <= data_df['col_39']))
)
valid_index

timestamp            num
2017-07-11 00:00:00  0      False
                     1      False
                     2      False
                     3      False
                     4      False
                            ...
2020-11-30 19:00:00  658    False
                     659    False
                     660    False
                     661    False
                     662    False
Length: 7370571, dtype: bool

In [13]:
data_valid = data_df[data_df.not_void & data_df.not_edge & data_df.not_night & data_df.valid]

In [17]:
data_dense = data_valid[data_valid.is_dense]

In [20]:
len(data_valid)

2126278

In [22]:
len(np.unique(data_valid.index.get_level_values('timestamp').date))

599

In [19]:
len(data_dense)

36322

In [21]:
len(np.unique(data_dense.index.get_level_values('timestamp').date))

335

In [ ]:
for ts in timestamps[10:20]:
#     full_arr = Image.open(path_all.at[ts, 'path_band1']).convert('L')
#     fig = plt.figure(figsize=(30, 60))
#     ax0 = fig.add_subplot(111)
#     ax0.imshow(full_arr, cmap='gray', vmin=0, vmax=255)
#     ax0.set_xticks(np.arange(0, side_len*index_shape[1], side_len))
#     ax0.set_xticklabels(np.arange(index_shape[1]))
#     ax0.set_yticks(np.arange(0, side_len*index_shape[0], side_len))
#     ax0.set_yticklabels(np.arange(index_shape[0]))
#     ax0.grid()
#     plt.show()
    imarr = np.full(
        shape=(side_len*index_shape[0], side_len*index_shape[1]), 
        fill_value=255
    )
    for num in data_show.loc[ts].index:
        row = data_show.loc[(ts, num)]
        i, j = np.unravel_index(indices=num, shape=index_shape)
        im = Image.open(row.path_band1).convert('L')
        imarr[i*side_len:(i+1)*side_len, j*side_len:(j+1)*side_len] = im
    fig = plt.figure(figsize=(30, 60))
    ax1 = fig.add_subplot(111)
    ax1.imshow(imarr, cmap='gray', vmin=0, vmax=255)
    ax1.set_xticks(np.arange(0, side_len*index_shape[1], side_len))
    ax1.set_xticklabels(np.arange(index_shape[1]))
    ax1.set_yticks(np.arange(0, side_len*index_shape[0], side_len))
    ax1.set_yticklabels(np.arange(index_shape[0]))
    ax1.grid()
    plt.show()